routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

 Route::get('/privacy-policy', 'PolicyController@show');

Auth::routes(['register' => false]);
// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

//Route::get('/test/query-string', 'TestController@getQueryString');
//
//Route::get('/test/payment_method', 'TestController@payment_methods');
//Route::post('/test/payment_method', 'TestController@add_payment_methods');
//
//Route::get('/test/order', 'TestController@order');
//Route::post('/test/submit_order', 'TestController@submit_order');
//Route::post('/test/pay_order', 'TestController@pay_order');

Route::group(['middleware' => ['auth', 'role:admin|retailer']], function () {
    Route::get('order/export', 'OrderController@export');
    Route::get('order/{id}', 'OrderController@print');
    Route::get('reports/sold/export', 'API\ReportsController@export');
	Route::get('{path?}', 'DashboardController@index')->where('path', '[\/\w\.-]*');
});

/* Webhook routes */
Route::group(['prefix' => 'webhooks', 'namespace' => 'Webhooks'], function(){
	Route::post('stripe/internal', 'StripeController@handle_internal');
	Route::post('stripe/connections', 'StripeController@handle_connections');
});

/* Retail routes */
// Route::group(['middleware' => ['auth', 'role:retailer']], function () {
// 	Route::get('/retails', 'RetailController@index')->name('retails.index');
// 	Route::get('/retails/create', 'RetailController@create')->name('retails.create');
// 	Route::post('/retails', 'RetailController@store')->name('retails.store');
// });

// Route::group(['prefix' => 'retail', 'middleware' => ['auth', 'role:retailer']], function () {
// 	Route::get('{path?}', 'RetailController@dashboard')->where('path', '[\/\w\.-]*')->name('retails.dashboard');
// });


/* Admin routes */
// Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role:admin']], function () {
// 	Route::get('{path?}', 'AdminController@index')->where('path', '[\/\w\.-]*');
// });

app/Order.php
<?php

namespace App;

use App\Scopes\OrderOwnerScope;
use App\Scopes\OwnerScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class Order extends Model
{
    use SoftDeletes;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['paid_at', 'shipped_at', 'completed_at', 'created_at', 'updated_at', 'deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id',
        'payment_id',
        'retailer_id',
        'location_id',
        'queue',
        'total_price',
        'grandtotal_price',
        'total_fee',
        'is_delivery',
        'table_number',
        'description',
        'charge_type',
        'status',
        'tips',
        'paid_at',
        'customer_fee_percent',
        'customer_fee_number',
        'retailer_fee_percent',
        'retailer_fee_number',
        'currency',
        'delivery_address',
        'phone_number',
        'home_delivery_price',
        'discount',
        'grandtotal_price_before_discount',
        'total_price_before_discount',
        'discount_sum',
        'shipped_at',
        'completed_at'
    ];

    /**
     * The "booting" method of the model.
     *
     * @return void
     */
    public static function boot()
    {
        parent::boot();

        static::addGlobalScope(new OrderOwnerScope());
    }

    /**
     * Scope a query to only include popular users.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopePaid($query)
    {
        return $query->where('paid', 1);
    }

    /**
     * Get the user for the item.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo('App\User', 'user_id')->withTrashed();
    }

    /**
     * Get the user for the item.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function retailer()
    {
        return $this->belongsTo('App\User', 'retailer_id')->withTrashed();
    }

    /**
     * Get the location for the item.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function location()
    {
        return $this->belongsTo('App\Location')->withoutGlobalScope('App\Scopes\OwnerScope')->withTrashed();
    }

    /**
     * Get order items for the order.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function order_items()
    {
        return $this->hasMany('App\OrderItem')->with('item')->withTrashed();
    }

    /**
     * Get the created_at and return formatted date value
     *
     * @param string $value
     * @return string
     */
    public function getCreatedAtAttribute($value)
    {
        return Carbon::parse($value)->toDateTimeString();
    }

    public function getCreatedAtPrintAttribute($value)
    {
        return Carbon::parse($value)->format('M j g:iA');
    }

    public function getCreatedAtObjectAttribute()
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $this->created_at);
    }

    public function getCurrencySymbolAttribute($value)
    {
        return Location::currencyToSymbol($this->currency);
    }

    public static function handleDate($date, $offset, $format = 'Y/m/d', $start = false)
    {
        if (empty($date)) {
            return $date;
        }
        if ($start) {
            return Carbon::createFromFormat($format, $date)
                    ->format('Y-m-d') . ' ' . Carbon::createFromTime(3, 0, 0)
                    ->addMinutes((int)$offset)->format('H:i:s');
        } else {
            return Carbon::createFromFormat($format, $date)
                    ->addDay()->format('Y-m-d') . ' ' . Carbon::createFromTime(3, 0, 0)
                    ->addMinutes((int)$offset)->format('H:i:s');
        }
    }

    public static function validateOrder(
        $items,
        $total_price,
        $grand_total_price,
        $tip,
        $total_fee,
        $location,
        $delivery_price,
        $discount
    ) {
        $summ = 0;
        $price_name = 'price_' . $location->currency;
        $discount_sum = 0;
        foreach ($items as $item) {
            /** @var $item_obj Item */
            $item_obj = Item::withoutGlobalScope(OwnerScope::class)->findOrFail($item['id']);
            $categories_check = DB::table('location_has_categories')
                ->selectRaw('1')
                ->where('category_id', $item_obj->category_id)
                ->whereNull('time_start')
                ->whereNull('time_end')
                ->where('location_id', $location->id)->exists();
            $summ += $item['quantity'] * $item_obj->$price_name;
            if ($categories_check && $discount) {
                $discount_sum += $item['quantity'] * round($item_obj->$price_name * $discount / 100, 2);
            }
            if (isset($item['addons'])) {
                foreach ($item['addons'] as $addon) {
                    $summ += $item['quantity'] * $addon['price'];
                    if ($categories_check && $discount) {
                        $discount_sum += $item['quantity'] * round($addon['price'] * $discount / 100, 2);
                    }
                }
            }
        }

        $valid_total = $summ + $tip + $delivery_price - $discount_sum;
        $valid_total_fee = $location->real_price_config->calculateFee($valid_total, $location);
        $valid_grand_total = $valid_total + $valid_total_fee;
        $return = [
            'valid' => true,
            'discount_sum' => $discount_sum,
            'valid_total' => $valid_total,
            'valid_grand_total' => $valid_grand_total,
            'valid_total_fee' => $valid_total_fee
        ];
        if (round($total_price, 2) != round($valid_total, 2)
            || round($valid_grand_total, 2) != round($grand_total_price, 2)
            || round($valid_total_fee, 2) != round($total_fee, 2)
        ) {
            $return['valid'] = false;
        }
        return $return;
    }

    public static function generateReportSoldQuery($user_id, $location, $date_start, $date_end, $sort_key, $sort_order)
    {
        $items = DB::table('order_items')
            ->selectRaw('categories.name as category,
             orders.currency,
              item_name as item,
               JSON_ARRAYAGG(json_object("addons", addons -> "$.*", "quantity", quantity)) as addons,
               sum(order_items.quantity) as quantity,
                avg(item_price) as price, orders.currency, sum(item_price*order_items.quantity) as total  ')
            ->join('orders', 'orders.id', '=', 'order_items.order_id')
            ->join('items', 'items.id', '=', 'order_items.item_id')
            ->leftJoin('categories', 'items.category_id', '=', 'categories.id')
            ->join('locations', 'locations.id', '=', 'orders.location_id')
            ->where('orders.retailer_id', '=', $user_id)
            ->where('orders.status', '!=', 6)
            ->where('orders.status', '!=', 1)
            ->groupBy('order_items.item_id');
        if ($location) {
            $items = $items->where('orders.location_id', '=', $location);
        } else {
            $items = $items->whereRaw('0=1');
        }
        $items = $items->when(!empty($date_start) && !empty($date_end), function ($query) use ($date_start, $date_end) {
            $query->whereBetween('orders.created_at', [$date_start, $date_end]);
        });
        if (isset($sort_order) && isset($sort_key)
            && !empty($sort_key) && !empty($sort_order)) {
            $items->orderBy($sort_key, $sort_order);
        } else {
            $items->orderBy('orders.created_at', 'desc');
        }
        return $items;
    }

    public function getStatusName()
    {
        $map = [
            0 => 'pending',
            1 => 'failed',
            2 => 'ready for collection',
            3 => 'ready for delivery',
            4 => 'completed',
            5 => 'home delivery',
            6 => 'refund',
        ];
        return $map[$this->status];
    }

    public function getDrinkAppFeeAttribute()
    {
        if ($this->charge_type === 'custom') {
            return floor(($this->total_price * $this->retailer_fee_percent / 100 + $this->retailer_fee_number) * 100) / 100;
        } else {
            return floor(($this->total_price * $this->retailer_fee_percent / 100 + $this->retailer_fee_number) * 100) / 100;
        }
    }

    public function getOrderRevenueAttribute()
    {
        if ($this->charge_type === 'custom') {
            return floor(($this->total_price - ($this->total_price * $this->retailer_fee_percent / 100 + $this->retailer_fee_number)) * 100) / 100;
        } else {
            if ($this->net) {
                if (empty($this->net_in_order_currency)) {
                    return $this->net / 100;
                } else {
                    return $this->net_in_order_currency / 100;
                }
            } else {
                return $this->total_price;
            }
        }
    }

    public function getStripeFeeAttribute()
    {
        if ($this->charge_type === 'custom') {
            return floor(($this->total_price * $this->retailer_fee_percent / 100 + $this->retailer_fee_number) * 100) / 100 + $this->total_fee;
        } else {
            if ($this->fee_in_order_currency) {
                if (empty($this->fee_in_order_currency)) {
                    return round($this->total_price - $this->net / 100, 2);
                } else {
                    return $this->fee_in_order_currency / 100;
                }
            } else {
                return 0;
            }
        }
    }

resources/views/dashboard.blade.php
<!-- @php
$config = [
    'appName' => config('app.name'),
    'locale' => $locale = app()->getLocale(),
    'locales' => config('app.locales')
];
@endphp -->
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito|Rubik:300,500,400" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
    <script src="{{asset('epson_js/epos-2.14.0.js')}}" defer></script>
    {{-- Global configuration object --}}
    <script>window.config = @json($config);</script>

    <script type="text/javascript">
        window.Drink = {
            csrfToken: "{{ csrf_token() }}"
        }
        window.User = {!! Auth::user() !!}
        window.Language = "{{ config('app.locale') }}"
    </script>
</head>
<body>
    <div id="app"></div>

    {{-- Load the application scripts --}}
    @if (app()->isLocal())
        <!-- <script src="{{ mix('js/app.js') }}"></script> -->
    @else
        <script src="{{ mix('js/manifest.js') }}"></script>
        <script src="{{ mix('js/vendor.js') }}"></script>
        <script src="{{ mix('js/app.js') }}"></script>
    @endif

    {{-- Google Map API --}}
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAduOnmBGeS7MTOREPwMNGGHouG9dOf8xc&libraries=places"
        async defer></script>

    {{-- Stripe.js --}}
    <script src="https://js.stripe.com/v3/"></script>
</body>
</html>

resources/views/home.blade.php
@extends('layouts.home')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                {{-- <div class="card-header">Dashboard</div> --}}

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@php
$config = [
    'appName' => config('app.name'),
    'locale' => $locale = app()->getLocale(),
    'locales' => config('app.locales'),
    'githubAuth' => config('services.github.client_id'),
];

$polyfills = [
    'Promise',
    'Object.assign',
    'Object.values',
    'Array.prototype.find',
    'Array.prototype.findIndex',
    'Array.prototype.includes',
    'String.prototype.includes',
    'String.prototype.startsWith',
    'String.prototype.endsWith',
];
@endphp
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>{{ config('app.name') }}</title>

  <link rel="stylesheet" href="{{ mix('css/app.css') }}">
</head>
<body>
  <div id="app"></div>

  {{-- Global configuration object --}}
  <script>window.config = @json($config);</script>

  {{-- Polyfill JS features via polyfill.io --}}
  {{-- <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features={{ implode(',', $polyfills) }}"></script> --}}

  {{-- Load the application scripts --}}
  @if (app()->isLocal())
    <script src="{{ mix('js/app.js') }}"></script>
  @else
    <script src="{{ mix('js/manifest.js') }}"></script>
    <script src="{{ mix('js/vendor.js') }}"></script>
    <script src="{{ mix('js/app.js') }}"></script>
  @endif
</body>
</html>

resources/views/order.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <style>
        * {
            font-size: 12px;
            font-family: 'Times New Roman';
            -webkit-print-color-adjust: exact !important;
        }

        table {
            border-top: 1px solid black;
            border-collapse: collapse;
        }
        .border {
            border-top: 1px solid black;
            border-collapse: collapse;
        }
        .headers {
            color: black;
        }

        .title {
            font-weight: 700;
        }

        td.name,
        th.name {
            width: 130px;
            max-width: 130px;
        }

        td.quantity,
        th.quantity {
            width: 25px;
            max-width: 25px;
            font-weight: 700;
            word-break: break-all;
        }

        td.check,
        th.check {
            width: 25px;
            max-width: 25px;
            word-break: break-all;
        }

        .centered {
            text-align: center;
            align-content: center;
        }

        .order {
            width: 155px;
            max-width: 155px;
        }

        img {
            max-width: inherit;
            width: inherit;
        }
    </style>
</head>
<body>
<div class="order">
    <p class="headers">
        @if ($order->table)
            To table: {{$order->table}}
        @elseif($order->delivery_address)
            Delivery
        @else
            Collect at bar
        @endif
    </p>
    <p class="headers">{{$order->created_at_print}}</p>
    <p class="headers">Queue number: {{$order->queue}}</p>
    <p class="title">Order details: </p>
    <table>
        @if ($order->phone_number)
            <tr class="border">
                <td>Number:</td>
                <td>{{$order->phone_number}}</td>
            </tr>
        @endif
        @if ($order->delivery_address)
                <tr class="border">
                <td>Address:</td>
                <td>{{$order->delivery_address}}</td>
            </tr>
        @endif
        <tr class="border">
            <td>Customer:</td>
            <td>{{$order->user->name}}</td>
        </tr>
        @if(!empty($order->description))
            <tr class="border">
                <td>Note:</td>
                <td>{{$order->description}}</td>
            </tr>
        @endif
    </table>
    <p class="title">Items: </p>
    <table>
        <tbody>
        @foreach($order->order_items as $item)
            <tr class="border">
                <td class="quantity">{{$item->quantity}}X</td>
                <td class="name">{{$item->item_name}}</td>
            </tr>
            @if($item->options)
                @foreach($item->options as $option)
                    <tr>
                        <td></td>
                        <td class="name" style="font-style: italic">{{$option['name']}}: {{$option['value']}}</td>
                    </tr>
                @endforeach
            @endif
            @if($item->addons)
                @foreach($item->addons as $addon)
                    <tr>
                    <td>+ {{$item->quantity}}</td>
                    <td class="name"  style="font-style: italic">{{$addon['name']}}</td>
                    </tr>
                @endforeach
            @endif
        @endforeach
        </tbody>
    </table>
</div>
<script>
    // window.print();
    window.onclick = function () {
        window.close();
    };
    // window.onafterprint = function () {
    //     window.parent.focus();
    //     window.close();
    // }
</script>
</body>
</html>